language: python

python:
  - "3.6"

env:
  global:
    - DOWNLOADS=$HOME/downloads
    - LIB=$HOME/lib
    - DERIVATIVES=tests/data/derivatives
    - INSTALL=$HOME/bin
    - SOURCE_PATH=$TRAVIS_BUILD_DIR/docs/source
    - API_PATH=$SOURCE_PATH/api
    - BUILD_PATH=$TRAVIS_BUILD_DIR/docs/build
    - HTML_PATH=$TRAVIS_BUILD_DIR/docs/build/html

cache: 
 - directories:
   - $HOME/.cache/pip

before_install:
  - sudo apt-get update -qq

  # install fsl
  - bash <(wget -q -O- http://neuro.debian.net/_files/neurodebian-travis.sh)
  - sudo apt-get -y update && sudo apt-get install -y -qq fsl-core
  - source /etc/fsl/fsl.sh
  - export FSLOUTPUTTYPE=NIFTI_GZ

  # install freesurfer
  - mkdir $DERIVATIVES/freesurfer -p
  - wget -q --directory-prefix=$DOWNLOADS https://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/6.0.1/freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.1.tar.gz ;
  - mkdir $LIB -p
  - tar 
    -xf $DOWNLOADS/freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.1.tar.gz 
    -C $LIB 
    --exclude='freesurfer/trctrain' 
    --exclude='freesurfer/subjects/fsaverage_sym' 
    --exclude='freesurfer/subjects/fsaverage3' 
    --exclude='freesurfer/subjects/fsaverage4'
    --exclude='freesurfer/subjects/fsaverage5' 
    --exclude='freesurfer/subjects/fsaverage6' 
    --exclude='freesurfer/subjects/cvs_avg35' 
    --exclude='freesurfer/subjects/cvs_avg35_inMNI152' 
    --exclude='freesurfer/subjects/V1_average' 
    --exclude='freesurfer/average/mult-comp-cor' 
    --exclude='freesurfer/lib/cuda' 
    --exclude='freesurfer/lib/qt' 
    --exclude='freesurfer/lib/tcltktixblt'
    --exclude='freesurfer/lib/vtk' 
    --exclude='freesurfer/diffusion' 
    freesurfer ;
  - echo -e $FREESURFER_LICENSE > $LIB/freesurfer/license.txt
  - ls -l $LIB/freesurfer
  - export FREESURFER_HOME=$LIB/freesurfer
  - source $FREESURFER_HOME/SetUpFreeSurfer.sh

  # geckodriver
  #- json=$(curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest)
  #- url=$(echo "$json" | jq -r '.assets[].browser_download_url | select(contains("linux64"))')
  - url=https://github.com/mozilla/geckodriver/releases/download/v0.20.1/geckodriver-v0.20.1-linux64.tar.gz
  - curl -s -L "$url" | tar -xz
  - chmod +x geckodriver
  - mkdir $INSTALL -p
  - mv geckodriver $INSTALL
  - export PATH=$INSTALL:$PATH

install:

  # install requirements
  - pip install numpy scipy pyqt5
  - pip install cython
  - pip install nibabel vispy wonambi bidso plotly popeye
  - pip install -e git+https://github.com/gpiantoni/exportimages.git#egg=exportimages  # this should be in pypi
  - pip install pytest pytest-qt pytest-cov codecov
  - pip install -e .

before_script:
  - export DISPLAY=:99.0;
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render;

script:
  - python -c "import vispy; print(vispy.sys_info())"
  - py.test --cov=boavus tests
  - coverage combine  # multiprocessing
  - find tests/data -type f -printf "\n%TY/%Tm/%Td %TH:%TM:%TS\t%s\n" -exec md5sum \{\} \;

after_success:
  - codecov
  - pip install sphinx sphinx_rtd_theme
  - sphinx-apidoc -fMeT -o $API_PATH boavus
  - sphinx-build -T -b html -d $BUILD_PATH/doctrees $SOURCE_PATH $HTML_PATH

notifications:
  email: false

deploy:
 - provider: pages
   skip_cleanup: true
   target_branch : gh-pages
   local_dir : docs/build/html
   repo : gpiantoni/boavus
   github_token : $GITHUB_TOKEN
