language: python

python:
  - "3.6"

env:
  global:
    - HTML_PATH=docs/build/html

cache: 
 - directories:
   - $HOME/.cache/pip

before_install:
 - sudo apt-get update -qq

install:

 # install requirements
 - pip install Cython
 - pip install wonambi nibabel bidso scikit-image
 - pip install -e git+https://github.com/kdesimone/popeye.git#egg=popeye
 - pip install pytest pytest-cov codecov
 - pip install -e .

script:
 - ./make.py --tests
 - find tests/simulated -type f -printf "\n%TY/%Tm/%Td %TH:%TM:%TS\t%s\n" -exec md5sum \{\} \;

after_success:
 - codecov
 - pip install sphinx sphinx_rtd_theme
 - ./make.py --docs

notifications:
  email: false

deploy:
 - provider: pypi
   user: $PYPI_USER
   password: $PYPI_PASSWORD
   on:
     tags: true
 - provider: pages
   skip_cleanup: true
   target_branch : gh-pages
   local_dir : $HTML_PATH
   repo : gpiantoni/sanajeh
   github_token : $GITHUB_TOKEN
