language: python

python:
  - "3.6"

env:
  global:
    - DOWNLOADS=$HOME/downloads
    - LIB=$HOME/lib
    - DERIVATIVES=tests/data/derivatives
    - INSTALL=$HOME/bin
    - SOURCE_PATH=$TRAVIS_BUILD_DIR/docs/source
    - API_PATH=$SOURCE_PATH/api
    - BUILD_PATH=$TRAVIS_BUILD_DIR/docs/build
    - HTML_PATH=$TRAVIS_BUILD_DIR/docs/build/html

cache: 
 - directories:
   - $HOME/.cache/pip

before_install:
  - sudo apt-get update -qq

install:

  # install requirements
  - pip install numpy nibabel
  - pip install pytest pytest-cov codecov
  - pip install -e .

script:
  - py.test --cov=sanajeh tests
  - coverage combine  # multiprocessing
  - find tests/simulated -type f -printf "\n%TY/%Tm/%Td %TH:%TM:%TS\t%s\n" -exec md5sum \{\} \;

after_success:
  - codecov

notifications:
  email: false
