language: python

python:
  - "3.6"

env:
  global:
    - DOWNLOADS=$HOME/downloads
    - LIB=$HOME/lib
    - DERIVATIVES=tests/data/derivatives
    - INSTALL=$HOME/bin
    - SOURCE_PATH=$TRAVIS_BUILD_DIR/docs/source
    - API_PATH=$SOURCE_PATH/api
    - BUILD_PATH=$TRAVIS_BUILD_DIR/docs/build
    - HTML_PATH=$TRAVIS_BUILD_DIR/docs/build/html

cache: 
 - directories:
   - $HOME/.cache/pip

before_install:
 - sudo apt-get update -qq

install:

 # install requirements
 - pip install Cython
 - pip install wonambi nibabel bidso popeye
 - pip install pytest pytest-cov codecov
 - pip install -e .

script:
 - py.test --cov=sanajeh tests
 - find tests/simulated -type f -printf "\n%TY/%Tm/%Td %TH:%TM:%TS\t%s\n" -exec md5sum \{\} \;

after_success:
 - codecov
 - pip install sphinx sphinx_rtd_theme
 - sphinx-apidoc -fMeT -o $API_PATH sanajeh
 - sphinx-build -T -b html -d $BUILD_PATH/doctrees $SOURCE_PATH $HTML_PATH

notifications:
  email: false

deploy:
 - provider: pypi
   user: $PYPI_USER
   password: $PYPI_PASSWORD
   on:
     tags: true
 - provider: pages
   skip_cleanup: true
   target_branch : gh-pages
   local_dir : docs/build/html
   repo : gpiantoni/sanajeh
   github_token : $GITHUB_TOKEN
